[workspace]
resolver = "2"
members = [
    "feu-noyau",
    "feu-application",
    "feu-tui"]

[workspace.package]
version = "0.0.7"
license = "GPL-3.0-or-later"

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
doc_markdown = "allow"
must_use_candidate = "allow"
similar_names = "allow"
too_many_lines = "allow"

[profile.release]
strip = true
